### ISSUE TITLE
被特定了

### ISSUE THREAD

**Issue by Womsxd** [1582421598/WTF_LAV#1]
马上就到你github上面 ×
已经Follow了 √
![image](https://user-images.githubusercontent.com/51043917/91039441-236e9800-e63f-11ea-9d5e-6f935e8a30b6.png)

**Comment by winxpqq955** [comment]
![680748975623766026](https://user-images.githubusercontent.com/22725877/91039045-6d0ab300-e63e-11ea-9dcb-a0722e39399e.png)

**Comment by KawaiiTamako** [comment]
![image](https://user-images.githubusercontent.com/51044119/91039144-83dbe600-e5fb-11ea-8543-b5a48c378b85.png)

**Comment by jiajiaxd** [comment]
牛

**Comment by jiajiaxd** [comment]
![image](https://user-images.githubusercontent.com/51043917/91039441-236e9800-e63f-11ea-9d5e-6f935e8a30b6.png)
